"""remove profile_color from account

Revision ID: 6dfc4098d8de
Revises: c41bee9b6f62
Create Date: 2026-01-31 15:22:10.081914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfc4098d8de'
down_revision = 'c41bee9b6f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('profile_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_color', sa.VARCHAR(length=7), nullable=True))

    # ### end Alembic commands ###
